[package]
name = "bron_kerbosch"
version = "1.0.0"
authors = ["Stein Somers <git@steinsomers.be>"]
edition = "2024"

[dependencies]
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
fnv = "1.0.7"
hashbrown = "0.16.1"
rand = "0.10.0"

[dev-dependencies]
proptest = "1.10.0"
rand_chacha = "0.10.0"
