[package]
name = "bron_kerbosch"
version = "1.0.0"
authors = ["Stein Somers <git@steinsomers.be>"]
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
fnv = "1.0.7"
hashbrown = "0.16.0"
rand = "0.9.2"

[dev-dependencies]
proptest = "1.9.0"
rand_chacha = "0.9.0"
